# Generated by Django 4.2.7 on 2023-11-10 22:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="blog",
            name="content",
            field=mdeditor.fields.MDTextField(default="test"),
            preserve_default=False,
        ),
    ]
