# Generated by Django 4.2.7 on 2023-11-10 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_category_options_blog_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="image",
            new_name="cover",
        ),
    ]
