# Generated by Django 4.2.7 on 2023-11-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_image_blog_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title_en", models.CharField(max_length=250, verbose_name="Title")),
                ("title_uz", models.CharField(max_length=250, verbose_name="Title")),
                ("title_ru", models.CharField(max_length=250, verbose_name="Title")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
            },
        ),
    ]
