# Generated by Django 4.2.7 on 2023-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_tag_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=250)),
                ("value", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(to="api.productfeature"),
        ),
    ]
