# Generated by Django 4.2.7 on 2023-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_productfeature_product_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfeature",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="title",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="value",
        ),
        migrations.AddField(
            model_name="productfeature",
            name="title_en",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="title_ru",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="title_uz",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Title"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="value_en",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Value"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="value_ru",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Value"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productfeature",
            name="value_uz",
            field=models.CharField(
                default="test", max_length=250, verbose_name="Value"
            ),
            preserve_default=False,
        ),
    ]
