# Generated by Django 4.2.7 on 2023-11-16 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_productfeature_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="features",
        ),
        migrations.AddField(
            model_name="productfeature",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="api.product",
            ),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
