# Generated by Django 4.2.7 on 2023-11-16 21:03

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_product_features_productfeature_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availability_status",
            field=models.IntegerField(
                choices=[(1, "Omborda mavjud"), (2, "Buyurtma orqali")], default=1
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cip_type",
            field=models.IntegerField(
                choices=[(1, "DAF"), (2, "EXW"), (3, "FCA")], default=1
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=mdeditor.fields.MDTextField(
                default="test", verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=mdeditor.fields.MDTextField(
                default="test", verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=mdeditor.fields.MDTextField(
                default="test", verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
