# Generated by Django 4.2.7 on 2023-11-29 23:14

import api.models.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_product_availability_status_product_cip_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banner_image_en",
                    models.FileField(upload_to="", verbose_name="banner"),
                ),
                (
                    "banner_image_uz",
                    models.FileField(upload_to="", verbose_name="banner"),
                ),
                (
                    "banner_image_ru",
                    models.FileField(upload_to="", verbose_name="banner"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, api.models.base.TranslatedFields),
        ),
    ]
