# Generated by Django 4.2.7 on 2023-11-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="product_url",
            field=models.CharField(default="test", max_length=500),
            preserve_default=False,
        ),
    ]
