# Generated by Django 4.2.7 on 2023-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_banner_product_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="banner_image_en",
            field=models.ImageField(upload_to="", verbose_name="banner"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="banner_image_ru",
            field=models.ImageField(upload_to="", verbose_name="banner"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="banner_image_uz",
            field=models.ImageField(upload_to="", verbose_name="banner"),
        ),
    ]
