# Generated by Django 4.2.7 on 2023-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
