# Generated by Django 4.2.7 on 2023-12-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_product_price_alter_product_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
            preserve_default=False,
        ),
    ]
