# Generated by Django 4.2.7 on 2023-12-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                limit_choices_to={"category_id": models.F("category_id")},
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subcategory",
            ),
        ),
    ]
