# Generated by Django 4.2.7 on 2023-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_remove_tag_product_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(default="", max_length=500),
        ),
    ]
