# Generated by Django 4.2.7 on 2023-12-14 19:58

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_remove_product_tags_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=mdeditor.fields.MDTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=mdeditor.fields.MDTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=mdeditor.fields.MDTextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(blank=True, max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(blank=True, max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
