# Generated by Django 4.2.7 on 2023-12-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_jwttoken_productimage_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_ru",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_uz",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.product",
            ),
        ),
    ]
