# Generated by Django 4.2.7 on 2023-12-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_product_short_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, default="")),
                ("image", models.ImageField(upload_to="", verbose_name="banner")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
