# Generated by Django 4.2.7 on 2023-12-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_product_background_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("company_name", models.CharField(max_length=255)),
                ("experience", models.IntegerField()),
                ("short_details", models.CharField(max_length=700)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("logo", models.FileField(upload_to="")),
                ("cooperational_status", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to",
                to="api.product",
                verbose_name="Related Products (for sets or complects)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description_en",
            field=models.TextField(default="", verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description_ru",
            field=models.TextField(default="", verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description_uz",
            field=models.TextField(default="", verbose_name="short description"),
        ),
    ]
