# Generated by Django 4.2.7 on 2024-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="cooperational_status",
            field=models.IntegerField(
                choices=[(1, "Resume"), (2, "Pause"), (3, "Stop")]
            ),
        ),
    ]
