# Generated by Django 4.2.7 on 2024-01-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.IntegerField(
                choices=[(1, "Uzb"), (2, "Eng"), (3, "Rus")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
