# Generated by Django 4.2.7 on 2024-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_product_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.IntegerField(
                choices=[(1, "uz"), (2, "en"), (3, "ru")], default=1
            ),
        ),
    ]
