# Generated by Django 4.2.7 on 2024-02-08 18:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_blog_created_at_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
    ]
