# Generated by Django 4.2.7 on 2024-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_alter_product_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.CharField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.CharField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.CharField(null=True, verbose_name="description"),
        ),
    ]
