# Generated by Django 4.2.7 on 2024-02-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0050_alter_product_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Not started"), (2, "Pending"), (3, "Finished")], default=1
            ),
        ),
    ]
