# Generated by Django 4.2.7 on 2024-02-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_order_description_order_notes_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
