# Generated by Django 4.2.7 on 2024-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0054_alter_customuser_role_smscode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundbanner",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
