# Generated by Django 4.2.7 on 2024-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_alter_backgroundbanner_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                to="api.product",
                verbose_name="Related Products (for sets or complects)",
            ),
        ),
    ]
