# Generated by Django 4.2.7 on 2024-03-16 20:56

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_alter_product_related_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=mdeditor.fields.MDTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=mdeditor.fields.MDTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=mdeditor.fields.MDTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
