# Generated by Django 4.2.7 on 2024-03-27 22:58

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_product_options_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title_en', models.CharField(max_length=250, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=250, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'LineCategory',
                'verbose_name_plural': 'LineCategories',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('video_link', models.CharField(max_length=250)),
                ('title_en', models.CharField(max_length=250, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=250, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=250, verbose_name='Title')),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('views', models.IntegerField()),
                ('title_en', models.CharField(max_length=250, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=250, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=250, verbose_name='Title')),
                ('short_description_en', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('short_description_uz', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('short_description_ru', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('long_description_en', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('long_description_uz', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('long_description_ru', mdeditor.fields.MDTextField(verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=mdeditor.fields.MDTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ru',
            field=mdeditor.fields.MDTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_uz',
            field=mdeditor.fields.MDTextField(verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('banner', models.ImageField(upload_to='')),
                ('views', models.IntegerField()),
                ('title_en', models.CharField(max_length=250, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=250, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=250, verbose_name='Title')),
                ('short_description_en', models.TextField()),
                ('short_description_uz', models.TextField()),
                ('short_description_ru', models.TextField()),
                ('long_description_en', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('long_description_uz', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('long_description_ru', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
