# Generated by Django 4.2.7 on 2024-04-21 07:15

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_product_options_remove_product_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='views',
            new_name='view_count',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='views',
            new_name='view_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=mdeditor.fields.MDTextField(verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ru',
            field=mdeditor.fields.MDTextField(verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_uz',
            field=mdeditor.fields.MDTextField(verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='line',
            name='long_description_en',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='long_description_ru',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='long_description_uz',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_en',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_ru',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_uz',
            field=mdeditor.fields.MDTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_en',
            field=mdeditor.fields.MDTextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_ru',
            field=mdeditor.fields.MDTextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_uz',
            field=mdeditor.fields.MDTextField(verbose_name='Short description'),
        ),
    ]
