# Generated by Django 4.2.7 on 2024-04-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_rename_views_line_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.linecategory'),
        ),
    ]
