# Generated by Django 4.2.7 on 2024-04-21 11:07

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_line_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description_en',
            field=mdeditor.fields.MDTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_ru',
            field=mdeditor.fields.MDTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_uz',
            field=mdeditor.fields.MDTextField(verbose_name='description'),
        ),
    ]
