# Generated by Django 4.2.7 on 2024-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_video_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='short_description_en',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='short_description_ru',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='short_description_uz',
            field=models.TextField(verbose_name='Short description'),
        ),
    ]
