# Generated by Django 4.2.7 on 2024-06-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_line_short_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
