# Generated by Django 4.2.7 on 2024-06-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_blog_content_en_alter_blog_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.backgroundbanner'),
        ),
    ]
