# Generated by Django 4.2.7 on 2024-06-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_product_description_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='value_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Value'),
        ),
    ]
