# Generated by Django 4.2.7 on 2024-06-30 22:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_productfeature_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='long_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='long_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='long_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='line',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='long_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Short description'),
        ),
    ]
