# Generated by Django 4.2.7 on 2024-06-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_line_long_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
    ]
