# Generated by Django 4.2.7 on 2024-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_product_short_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Unapproved Product',
                'verbose_name_plural': 'Unapproved Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cip_type',
            field=models.IntegerField(choices=[(1, 'DAF'), (2, 'EXW'), (3, 'FCA'), (4, 'CPT'), (5, 'CIP'), (6, 'DAP'), (7, 'DPU'), (8, 'DDP'), (9, 'FAS'), (10, 'FOB'), (11, 'CFR'), (12, 'CIF')], default=1),
        ),
    ]
