# Generated by Django 4.2.7 on 2024-09-14 09:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_unapprovedproduct_product_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('title_uz', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('short_description_en', models.TextField(null=True, verbose_name='short description')),
                ('short_description_uz', models.TextField(null=True, verbose_name='short description')),
                ('short_description_ru', models.TextField(null=True, verbose_name='short description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
