# Generated by Django 4.2.7 on 2024-09-14 11:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='short_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='short details'),
        ),
    ]
