# Generated by Django 4.2.7 on 2024-11-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_supplier_short_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='image',
        ),
        migrations.AddField(
            model_name='line',
            name='cip_type',
            field=models.IntegerField(choices=[(1, 'DAF'), (2, 'EXW'), (3, 'FCA'), (4, 'CPT'), (5, 'CIP'), (6, 'DAP'), (7, 'DPU'), (8, 'DDP'), (9, 'FAS'), (10, 'FOB'), (11, 'CFR'), (12, 'CIF')], default=1),
        ),
        migrations.AddField(
            model_name='line',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='max_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='min_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='yt_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
        migrations.CreateModel(
            name='LineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.line')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
