# Generated by Django 4.2.7 on 2024-11-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_remove_line_image_line_cip_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='show_supplier_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
        migrations.AddField(
            model_name='linecategory',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
