# Generated by Django 4.2.7 on 2024-11-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_line_approved_line_note_line_show_supplier_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linecategory',
            options={'ordering': ['order'], 'verbose_name': 'LineCategory', 'verbose_name_plural': 'LineCategories'},
        ),
        migrations.AddField(
            model_name='line',
            name='tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
