# Generated by Django 4.2.7 on 2024-11-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_linecategory_options_line_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('file', models.FileField(upload_to='line_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.line')),
            ],
            options={
                'verbose_name': 'Line Document',
                'verbose_name_plural': 'Line Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
