# Generated by Django 4.2.7 on 2025-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_category_description_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_cost_in_uzs',
            field=models.BooleanField(default=True),
        ),
    ]
