# Generated by Django 4.2.7 on 2025-02-17 16:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_product_show_cost_in_uzs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='meta_description',
            new_name='meta_description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='meta_keywords',
            new_name='meta_keywords_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='meta_title',
            new_name='meta_title_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='meta_description',
            new_name='meta_description_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='meta_keywords',
            new_name='meta_keywords_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='meta_title',
            new_name='meta_title_en',
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
