# Generated by Django 4.2.7 on 2025-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_rename_description_category_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='meta_description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='meta_description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='meta_description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='meta_title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='meta_title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='meta_title'),
        ),
    ]
