# Generated by Django 4.2.7 on 2025-03-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_category_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='yt_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
