# Generated by Django 4.2.7 on 2025-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_productpricebasedonmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
