# Generated by Django 4.2.7 on 2025-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_productimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
    ]
