# Generated by Django 4.2.7 on 2025-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_product_options_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
