# Generated by Django 4.2.7 on 2025-03-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_productimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
    ]
