# Generated by Django 4.2.7 on 2025-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_productimage_options_remove_productimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='productpricebasedonmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
