# Generated by Django 4.2.7 on 2025-08-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.IntegerField(choices=[(1, 'uz'), (2, 'en'), (3, 'ru'), (4, 'all')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('USER', 'Foydalanuvchi'), ('COPYWRITER', 'Copywriter')], default='USER', max_length=10),
        ),
    ]
