from django.urls import path

from api.views import (
    ProductDetailAPIView,
    ProductListAPIView,
    BlogListAPIView,
    BlogDetailAPIView,
    PartnersLogoListAPIView,
    CategoryListApiView,
    SubCategoryListApiView,
    UserVerificationView,
    UserRegistrationView,
    GoogleLoginAPIView,
    BannerListApiView,
    LineListAPIView,
    LineDetailAPIView,
    LineCategoryListApiView,
    VideoListAPIView,
    WorkListAPIView,
    WorkDetailAPIView,
    LoginView,
)

urlpatterns = [
    path("auth/register/", UserRegistrationView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/phone-verification/", UserVerificationView.as_view()),
    path("auth/google/", GoogleLoginAPIView.as_view(), name="google_login"),
    path("banners/", BannerListApiView.as_view()),
    path("blog-posts/", BlogListAPIView.as_view()),
    path("blog-posts/<int:pk>/", BlogDetailAPIView.as_view()),
    path("line-posts/", LineListAPIView.as_view()),
    path("line-posts/<int:pk>/", LineDetailAPIView.as_view()),
    path("categories/", CategoryListApiView.as_view()),
    path("sub-categories/", SubCategoryListApiView.as_view()),
    path("line-categories/", LineCategoryListApiView.as_view()),
    path("partner-logos/", PartnersLogoListAPIView.as_view()),
    path("videos/", VideoListAPIView.as_view()),
    path("products/", ProductListAPIView.as_view()),
    path("products/<int:pk>/", ProductDetailAPIView.as_view()),
    path("works/", WorkListAPIView.as_view()),
    path("works/<int:pk>/", WorkDetailAPIView.as_view()),
]
